# Generated by Django 5.1.7 on 2025-08-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('manager', 'manager')], default='user', max_length=20)),
            ],
        ),
    ]
