# Generated by Django 5.1.7 on 2025-08-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_searchbook_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchbook_tbl',
            name='read',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
