# Generated by Django 5.1.7 on 2025-08-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_searchbook_tbl_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_tbl',
            name='read',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
