# Generated by Django 5.1.7 on 2025-08-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_book_tbl_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchBook_tbl',
        ),
    ]
