# Generated by Django 5.1.7 on 2025-08-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_readinglist_tbl_readinglistitem_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglistitem_tbl',
            name='reading_list',
        ),
        migrations.RemoveField(
            model_name='readinglistitem_tbl',
            name='book',
        ),
        migrations.DeleteModel(
            name='ReadingList_tbl',
        ),
        migrations.DeleteModel(
            name='ReadingListItem_tbl',
        ),
    ]
