# Generated by Django 5.1.7 on 2025-08-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_readinglist_tbl_readinglistitem_tbl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglistitem_tbl',
            name='reading_list',
        ),
        migrations.RemoveField(
            model_name='readinglistitem_tbl',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userpreferences_tbl',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReadingList_tbl',
        ),
        migrations.DeleteModel(
            name='ReadingListItem_tbl',
        ),
        migrations.DeleteModel(
            name='UserPreferences_tbl',
        ),
    ]
