# Generated by Django 5.1.7 on 2025-08-17 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_adminprofile_tbl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile_tbl',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminprofile_tbl',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminprofile_tbl',
            name='password',
        ),
        migrations.RemoveField(
            model_name='adminprofile_tbl',
            name='user',
        ),
        migrations.AddField(
            model_name='adminprofile_tbl',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookapp.book_tbl'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book_tbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
