# Generated by Django 5.1.7 on 2025-08-18 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_remove_adminprofile_tbl_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readinglist',
            unique_together={('user', 'book')},
        ),
    ]
