# Generated by Django 5.1.7 on 2025-08-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_alter_readinglist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readinglist',
            unique_together=set(),
        ),
    ]
