# Generated by Django 5.1.7 on 2025-08-18 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0015_alter_readinglist_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglist',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='readinglist',
            name='book',
        ),
        migrations.AddField(
            model_name='readinglist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='in_lists', to='bookapp.book_tbl'),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
