# Generated by Django 5.1.7 on 2025-08-19 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0017_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookapp.register_tbl'),
            preserve_default=False,
        ),
    ]
