# Generated by Django 5.1.7 on 2025-08-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0018_usersubscription_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingNook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('books', models.ManyToManyField(related_name='nooks', to='bookapp.book_tbl')),
            ],
        ),
    ]
