# Generated by Django 5.1.7 on 2025-08-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0019_readingnook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_tbl',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
