# Generated by Django 5.2.5 on 2025-09-15 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0021_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglist',
            name='books',
        ),
        migrations.RemoveField(
            model_name='readinglist',
            name='name',
        ),
        migrations.AddField(
            model_name='readinglist',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookapp.book_tbl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readinglist',
            name='qty',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.register_tbl'),
        ),
    ]
