# Generated by Django 5.2.5 on 2025-09-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0022_remove_readinglist_books_remove_readinglist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='name',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookapp.subscriptionplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.register_tbl'),
        ),
    ]
