# Generated by Django 5.2.5 on 2025-09-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0024_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingNook',
        ),
    ]
