# Generated by Django 5.2.5 on 2025-09-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0025_delete_readingnook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
