# Generated by Django 5.2.5 on 2025-09-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0027_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tbl',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
