# Generated by Django 5.2.5 on 2025-09-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0028_register_tbl_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_on', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book_tbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.register_tbl')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
