# Generated by Django 5.2.5 on 2025-09-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0029_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tbl',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
