# Generated by Django 5.2.5 on 2025-09-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0030_register_tbl_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_tbl',
            name='is_subscribed',
        ),
    ]
