# Generated by Django 5.2.5 on 2025-09-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0031_remove_register_tbl_is_subscribed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBook',
        ),
    ]
